# Generated by Django 4.0.1 on 2022-01-24 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=200, null=False, blank=False)),
                ('vat', models.CharField(editable=False, max_length=200, unique=True, null=False, blank=False)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('sector', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                                        primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]


