# Generated by Django 4.0.1 on 2022-01-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='VAT',
        ),
        migrations.AddField(
            model_name='company',
            name='vat',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, unique=True),
        ),
    ]
