# Generated by Django 4.0.1 on 2022-01-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyexternaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyexternaldata',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
