# Generated by Django 4.0.1 on 2022-01-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companyexternaldata_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyexternaldata',
            name='Website',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='companyexternaldata',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companyexternaldata',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companyexternaldata',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companyexternaldata',
            name='economy_sector',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
